USE powergirls;
--IPC
SELECT MAX(IPC) AS MAX_IPC FROM IPC1$DatosExternos_5;
SELECT MIN(IPC) AS MIN_IPC FROM IPC1$DatosExternos_5;
SELECT AÑO, AVG(IPC) AS PROMEDIO_IPC FROM IPC1$DatosExternos_5
GROUP BY AÑO;
SELECT AÑO, VAR(IPC) AS VARIANZA_IPC FROM IPC1$DatosExternos_5
GROUP BY AÑO;
SELECT AÑO, MES, IPC FROM IPC1$DatosExternos_5
WHERE IPC > 120;
--VARIACION ANUAL
SELECT MAX(VARIACION_ANUAL) AS MAX_VA FROM VA2_$DatosExternos_14;
SELECT MIN(VARIACION_ANUAL) AS MIN_VA FROM VA2_$DatosExternos_14;
SELECT AÑO, SQRT(VAR(VARIACION_ANUAL)) AS DESVIACION_VA FROM VA2_$DatosExternos_14
GROUP BY AÑO;
SELECT AÑO, VAR(VARIACION_ANUAL) AS VARIANZA_VA_AÑO FROM VA2_$DatosExternos_14
GROUP BY AÑO;
SELECT MES, VAR(VARIACION_ANUAL) AS VARIANZA_VA_MES FROM VA2_$DatosExternos_14
GROUP BY MES;
--VARIACION MENSUAL
SELECT MAX(VARIACION_MENSUAL) AS MAX_VM FROM VM4$DatosExternos_8;
SELECT MIN(VARIACION_MENSUAL) AS MIN_VM FROM VM4$DatosExternos_8;
SELECT AÑO, SQRT(VAR(VARIACION_MENSUAL)) AS DESVIACION_VM FROM VM4$DatosExternos_8
GROUP BY AÑO;
SELECT AÑO, MES, VARIACION_MENSUAL FROM VM4$DatosExternos_8
WHERE VARIACION_MENSUAL<=0;
--PRINCIPALES CIUDADES DE LA REGIÓN CARIBE
SELECT AÑO, AVG(VARIACION_ANUAL) AS VA_BAQ FROM BARRANQUILLA12$DatosExternos_8
GROUP BY AÑO;
SELECT MES, VAR(VARIACION_ANUAL) AS VARIANZA_BAQ_MES FROM BARRANQUILLA12$DatosExternos_8
GROUP BY MES;
SELECT AÑO, AVG(VARIACION_ANUAL) AS VA_CTG FROM CARTAGENA9$DatosExternos_10
GROUP BY AÑO;
SELECT MES, VAR(VARIACION_ANUAL) AS VARIANZA_CTG_MES FROM CARTAGENA9$DatosExternos_10
GROUP BY MES;
SELECT AÑO, AVG(VARIACION_ANUAL) AS VA_SM FROM SANTA_MARTA$DatosExternos_11
GROUP BY AÑO;
SELECT MES, VAR(VARIACION_ANUAL) AS VARIANZA_SM_MES FROM SANTA_MARTA$DatosExternos_11
GROUP BY MES;
SELECT AÑO, AVG(VARIACION_ANUAL) AS VA_RH FROM RIOHACHA6$DatosExternos_12
GROUP BY AÑO;
SELECT MES, VAR(VARIACION_ANUAL) AS VARIANZA_RH_MES FROM RIOHACHA6$DatosExternos_12
GROUP BY MES;
SELECT AÑO, MAX(VARIACION_ANUAL) AS MAX_VA_BQ FROM BARRANQUILLA12$DatosExternos_8
GROUP BY AÑO;
SELECT AÑO, MES, VARIACION_ANUAL FROM BARRANQUILLA12$DatosExternos_8 
WHERE VARIACION_ANUAL < 3;
--PRINCIPALES CIUDADES DE LA REGIÓN ANDINA
SELECT MAX(VARIACION_ANUAL) AS MAX_VA_BOG FROM BOGOTA1111$DatosExternos_1;
SELECT MIN(VARIACION_ANUAL) AS MIN_VA_BOG FROM BOGOTA1111$DatosExternos_1;
SELECT MES, VAR(VARIACION_ANUAL) AS VARIANZA_BOG_MES FROM BOGOTA1111$DatosExternos_1
GROUP BY MES;
SELECT MAX(VARIACION_ANUAL) AS MAX_VA_CALI FROM CALI10$DatosExternos_9;
SELECT MIN(VARIACION_ANUAL) AS MIN_VA_CALI FROM CALI10$DatosExternos_9;
SELECT MES, VAR(VARIACION_ANUAL) AS VARIANZA_CALI_MES FROM CALI10$DatosExternos_9
GROUP BY MES;
SELECT MAX(VARIACION_ANUAL) AS MAX_VA_MED FROM MEDELLIN7$DatosExternos_13;
SELECT MIN(VARIACION_ANUAL) AS MIN_VA_MED FROM MEDELLIN7$DatosExternos_13;
SELECT MES, VAR(VARIACION_ANUAL) AS VARIANZA_MED_MES FROM MEDELLIN7$DatosExternos_13
GROUP BY MES;
SELECT MAX(VARIACION_ANUAL) AS MAX_VA_MAN FROM MANIZALES8$DatosExternos_14;
SELECT MIN(VARIACION_ANUAL) AS MIN_VA_MAN FROM MANIZALES8$DatosExternos_14;
SELECT MES, VAR(VARIACION_ANUAL) AS VARIANZA_MAN_MES FROM MANIZALES8$DatosExternos_14
GROUP BY MES;
SELECT AÑO, MAX(VARIACION_ANUAL) AS MAX_VA_BOG FROM BOGOTA1111$DatosExternos_1
GROUP BY AÑO;
